import React from "react";
import { motion } from "framer-motion";
import { Card, CardContent } from "../../components/ui/card";
import { Button } from "../../components/ui/button";
import { ArrowRight } from "lucide-react";

const ProjectSindhuja = () => {
    return (
        <div className="bg-blue-50 min-h-screen py-10 px-5">
            <motion.div
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="text-center mb-8"
            >
                <h1 className="text-blue-800 text-4xl font-bold">
                    Project Sindhuja
                </h1>
                <p className="text-gray-600 mt-2">
                    Vamanie Parmita Energy (VPE Pvt. Ltd.) | Incubated at IITK |
                    Technology Partner: IITM
                </p>
            </motion.div>

            <div className="grid gap-8">
                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Introduction
                    </h2>
                    <p className="text-gray-700 mt-2">
                        Sindhuja-I is a futuristic product focused on generating
                        Green Energy by harnessing ocean waves. VP Energy plans
                        to tap 1 MW out of the 40 GW potential of 7500+ KM
                        Indian coastline by 2030.
                    </p>
                </motion.div>

                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Mega Carbon Footprint
                    </h2>
                    <p className="text-gray-700 mt-2">
                        CO<sub>2</sub> emitted in Mt from Thermal Power Plants
                        in India: 499 Mt (2010) ➡ 1104 Mt (2021)
                    </p>
                </motion.div>

                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Current Challenges & Our Solution
                    </h2>
                    <p className="text-gray-700 mt-2">
                        Challenges with Green Energy Generation:
                        <ul className="list-disc pl-5">
                            <li>Huge land requirement</li>
                            <li>Lack of 24x7 energy generation capabilities</li>
                            <li>Seasonal variation</li>
                            <li>Disruption of ecosystem</li>
                        </ul>
                        <br />
                        Solution: Green energy generated by harnessing wave
                        power of the ocean without generating a carbon
                        footprint.
                    </p>
                </motion.div>

                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Unique Selling Proposition
                    </h2>
                    <ul className="list-disc pl-5 text-gray-700">
                        <li>
                            First mover advantage with tested technology across
                            Vishakhapatnam Coast
                        </li>
                        <li>
                            Proprietary PAWEC technology for Indian coastal &
                            ocean conditions
                        </li>
                        <li>
                            Strategic applications in defense, petroleum, and
                            other industries
                        </li>
                        <li>Generate & sell carbon credits</li>
                    </ul>
                </motion.div>

                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Road to Success
                    </h2>
                    <p className="text-gray-700 mt-2">
                        <span className="font-bold">2020:</span> Inception,
                        Simulations & POC Testing (Rs. 1.6Cr grant)
                        <br />
                        <span className="font-bold">2025:</span> 100 kW pilot
                        <br />
                        <span className="font-bold">2030:</span> Empowering
                        India (Business Expansion)
                    </p>
                </motion.div>

                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Why Wave Energy?
                    </h2>
                    <table className="table-auto w-full text-left mt-2">
                        <thead>
                            <tr className="bg-blue-100">
                                <th className="px-4 py-2">Energy Sources</th>
                                <th className="px-4 py-2">Hydroelectric</th>
                                <th className="px-4 py-2">Solar</th>
                                <th className="px-4 py-2">Wind</th>
                                <th className="px-4 py-2">Hydrogen</th>
                                <th className="px-4 py-2">Wave</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td className="border px-4 py-2">
                                    Indicative PPA
                                </td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">Low</td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">Medium</td>
                            </tr>
                            <tr>
                                <td className="border px-4 py-2">
                                    Material & Infra Cost
                                </td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">Low</td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">Medium</td>
                            </tr>
                            <tr>
                                <td className="border px-4 py-2">
                                    Operation & Maintenance Cost
                                </td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">Low</td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">Low</td>
                            </tr>
                            <tr>
                                <td className="border px-4 py-2">
                                    Land Requirement
                                </td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">Low</td>
                            </tr>
                            <tr>
                                <td className="border px-4 py-2">
                                    Impact on Ecology
                                </td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">Medium</td>
                                <td className="border px-4 py-2">High</td>
                                <td className="border px-4 py-2">Low</td>
                            </tr>
                        </tbody>
                    </table>
                </motion.div>

                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Funding Requirement
                    </h2>
                    <p className="text-gray-700 mt-2">
                        Rs. 5Cr required for human resources, material,
                        manufacturing & operations.
                    </p>
                </motion.div>

                <motion.div
                    whileHover={{ scale: 1.05 }}
                    className="bg-white rounded-2xl overflow-hidden shadow-lg p-6"
                >
                    <h2 className="text-2xl font-semibold text-blue-800">
                        Contact Us
                    </h2>
                    <p className="text-gray-700 mt-2">
                        Call: +91-8977017707 | Email: vpenergy@gmail.com | Web:
                        https://vpewave.com
                    </p>
                </motion.div>
            </div>
        </div>
    );
};

export default ProjectSindhuja;
