import "./App.css";

// import { Inter } from "next/font/google";
// import localFont from "next/font/local";

import React, { useEffect } from "react";
import Header from "./components/ui/header";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import Footer from "./components/ui/footer";
import Home from "./pages/home";
import Services from "./pages/services/Services";
import PrivacyPolicy from "./pages/privacy-policy/Privacy_Policy";
import Careers from "./pages/careers/Careers";
import Contact from "./pages/contact/Contact";
import Aos from "aos";
import DigitalMarketing from "./pages/services/digital-marketing/digital-marketing";
import MediaPlanning from "./pages/services/media-planning-analytics/media-plan-analytics";
import DigitalTransformation from "./pages/services/digital-transformation/digital-transformation";
import ContentAndEngineering from "./pages/services/content-and-engineering/content-and-engg";
import ExperienceDesign from "./pages/services/experience-design/experience-design";
import ECommerce from "./pages/services/e-commerce-solutions/e-commerce";
import { ToastContainer } from "react-toastify";
import About from "./pages/about/About";
import Team from "./pages/Team/team";
import PortfolioPage from "./pages/Portfolio/portfolio";
import NewsPartnersPage from "./pages/newsAndPartners/newsAndPartners";
// import ProjectSindhuja from "./pages/IWE/iwe2025";
import IndiaEnergyWeek from "./pages/IWE/componet2";
// const inter = Inter({
//     subsets: ["latin"],
//     variable: "--font-inter",
//     display: "swap",
// });

// const nacelle = localFont({
//     src: [
//         {
//             path: "../public/fonts/nacelle-regular.woff2",
//             weight: "400",
//             style: "normal",
//         },
//         {
//             path: "../public/fonts/nacelle-italic.woff2",
//             weight: "400",
//             style: "italic",
//         },
//         {
//             path: "../public/fonts/nacelle-semibold.woff2",
//             weight: "600",
//             style: "normal",
//         },
//         {
//             path: "../public/fonts/nacelle-semibolditalic.woff2",
//             weight: "600",
//             style: "italic",
//         },
//     ],
//     variable: "--font-nacelle",
//     display: "swap",
// });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function App() {
    useEffect(() => {
        Aos.init({
            once: true,
            // disable: "phone",
            duration: 600,
            easing: "ease-out-sine",
        });
    }, []);
    return (
        <Router>
            <div
                className={`font-inter text-base text-gray-200 antialiased bg-gradient-to-r from-cyan-500 to-blue-500 w-full`} // TO be fixed: ${inter.variable} ${nacelle.variable}
            >
                <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
                    <Header />
                    {/* {children} */}
                    <Routes>
                        <Route path="/" Component={Home} />
                        <Route path="/services" Component={Services}>
                            {/* <Router> */}
                            {/* <Routes> */}
                            <Route
                                path="/services/"
                                Component={DigitalMarketing}
                            />
                            <Route
                                path="/services/digital-marketing"
                                Component={DigitalMarketing}
                            />
                            <Route
                                path="/services/content-and-engg"
                                Component={ContentAndEngineering}
                            />
                            <Route
                                path="/services/media-planning"
                                Component={MediaPlanning}
                            />
                            <Route
                                path="/services/digital-transformation"
                                Component={DigitalTransformation}
                            />
                            <Route
                                path="/services/experience-design"
                                Component={ExperienceDesign}
                            />
                            <Route
                                path="/services/e-commerce-solution"
                                Component={ECommerce}
                            />
                            {/* </Routes> */}
                            {/* </Router> */}
                        </Route>
                        <Route path="/portfolio" Component={PortfolioPage} />
                        <Route path="/contact" Component={Contact} />
                        <Route path="/team" Component={Team} />
                        <Route path="/iew-2025" Component={IndiaEnergyWeek} />

                        <Route
                            path="/news-and-partners"
                            Component={NewsPartnersPage}
                        />
                        <Route
                            path="/privacy-policy"
                            Component={PrivacyPolicy}
                        />
                        <Route path="/about" Component={About} />
                    </Routes>
                    <ToastContainer />

                    <Footer />
                </div>
            </div>
        </Router>
    );
}
